name: AWS OIDC Demo

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Assume RoleOIDC via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::592931547242:role/RoleOIDC
          aws-region: eu-central-1

      - name: Check first identity
        run: aws sts get-caller-identity

      - name: Assume DevelopmentDeploymentRole
        id: assume-dev
        run: |
          CREDS=$(aws sts assume-role \
          --role-arn arn:aws:iam::592931547242:role/DevelopmentDeploymentRole \
          --role-session-name github-development)

          echo "AWS_ACCESS_KEY_ID=$(echo "$CREDS" | jq -r '.Credentials.AccessKeyId')" >> "$GITHUB_ENV"
          echo "AWS_SECRET_ACCESS_KEY=$(echo "$CREDS" | jq -r '.Credentials.SecretAccessKey')" >> "$GITHUB_ENV"
          echo "AWS_SESSION_TOKEN=$(echo "$CREDS" | jq -r '.Credentials.SessionToken')" >> "$GITHUB_ENV"

      - name: Verify development role
        run: aws sts get-caller-identity
        
      - name: Upload deployment artifact
        run: |
          echo "commit=${GITHUB_SHA}" > deployment.txt

          aws s3 cp deployment.txt \
          s3://laboratori-4/releases/${GITHUB_SHA}.txt
